### ISSUE TITLE
Template for postgres

### ISSUE THREAD

**Issue by tlebeitsuk** [tlebeitsuk/hoster#112]
Layout for creating a new postgres database.

Fields:
- name
- password (or we can generate a password?)

**Comment by z3kkeen** [comment]
Vi kan använda en api som genererar password?

Som t.ex. [denhär](https://www.api-ninjas.com/api/passwordgenerator).

**Comment by tlebeitsuk** [comment]
Känns onödigt att använda en API för lösenord som inte behöver vara super komplicerade. Kan vara så enkelt som:

`Math.random().toString(36).substr(2, 8)
= "n5wgd2ad"`

_Källa: https://dev.to/itwasmattgregg/how-to-generate-a-random-id-in-javascript-without-a-library-50h9_
