### ISSUE TITLE
Name and logo

### ISSUE THREAD

**Issue by z3kkeen** [tlebeitsuk/hoster#34]

**Comment by WoIfey** [comment]
1. Projex
2. Hypervolt
3. Stordrive
4. Servertive

Några olika namn för vår projekt.

**Comment by WoIfey** [comment]
![image](https://github.com/user-attachments/assets/3a623cd5-a8b5-4184-a100-73b82af38ca5)
https://www.figma.com/design/Htns6MtZqdo5Veg2PdMrZ1/Logo?node-id=0-1&t=UH80EZNXq1tHESZL-1

Här är simpel logon för namnen jag gav.
Färg är från #36

**Comment by tlebeitsuk** [comment]
Jag gillar Projex!

**Comment by z3kkeen** [comment]
Hade en tanke att 'Hostess' skulle vara ett bra namn; det betyder exakt samma sak som hoster, men används inte av något annat server hosting företag (ingen kommer upp på googles första sida i alla fall), förklarar bra var servicen gör osv.

**Comment by tlebeitsuk** [comment]
> Hostess

Nice förslag! Bra point att det inte ska användas av andra och angående sökresultat.

Några till förslag i samma tema är [Majordomo](https://en.wikipedia.org/wiki/Majordomo), [Maître d'](https://en.wikipedia.org/wiki/Ma%C3%AEtre_d%27h%C3%B4tel), [Concierge](https://en.wikipedia.org/wiki/Concierge), [Porter](https://en.wikipedia.org/wiki/Doorman_(profession))...

**Comment by WoIfey** [comment]
![image](https://github.com/user-attachments/assets/4fd9edc8-df5c-4d79-8117-a6fd549fa166)
https://www.figma.com/design/Htns6MtZqdo5Veg2PdMrZ1/Hoster?node-id=0-1&t=swEqkfe8cPzPmMlK-1

Här är simpel logon för Hostess, Majordomo, Maître d', Concierge och Porter

**Comment by Steekmen** [comment]
Jag gillar namnet "Hostess" och typsnittet som i ”majordomo” och "concierge"

**Comment by WoIfey** [comment]
Håller vi med att vi väljer "Hostess"?
Ska vi ha färgen just nu eller någon annan färgschema

**Comment by z3kkeen** [comment]
jag gillar färg schemat i Concierge mera

**Comment by WoIfey** [comment]
![image](https://github.com/user-attachments/assets/d198b8b8-61d0-409d-a6df-99cbe8cadfa8)

Här är med Concierge färgschema
