### ISSUE TITLE
Wireframe: landing page

### ISSUE THREAD

**Issue by tlebeitsuk** [tlebeitsuk/hoster#4]
Wireframe design förslag på målsida (landing page) för appen.

**Comment by z3kkeen** [comment]
![image_2024-10-09_121728560](https://github.com/user-attachments/assets/54293b46-43f5-4fa5-bf6f-11c57a43445b)

![image](https://github.com/user-attachments/assets/15cbcbd3-1197-44c4-b99a-6ed3cbff1b22)

**Comment by tlebeitsuk** [comment]
Exempel:
- https://vite.dev
- https://vitest.dev
- https://uploadthing.com
- https://supabase.com

**Comment by z3kkeen** [comment]
login pages

![image_2024-10-09_122709587](https://github.com/user-attachments/assets/cc608b88-983b-43e8-a456-fe7f9c5c16d8)

![image](https://github.com/user-attachments/assets/32f72647-e293-4526-a13a-df4916184e93)
