### ISSUE TITLE
Format settings

### ISSUE THREAD

**Issue by WoIfey** [tlebeitsuk/hoster#44]
Alla har annorlunda inställningar i prettier som double quotes, single quotes och semicolon.
När vi gör pull request ändras det hela tiden för att prettier formatterar filerna på ett annat sätt.

Med en fil kan vi alla ha samma:
- https://prettier.io/docs/en/configuration.html

Vi kan också göra så att vi kan alla använda annorlunda prettier inställningar men när vi commitar blir det samma

**Comment by WoIfey** [comment]
Mina prettier inställningar är att ha inga semicolon och har med single quotes

**Comment by tlebeitsuk** [comment]
Räcker det med att vi skapar en [EditorConfig](https://github.com/fdaciuk/workflow-nextjs/blob/master/.editorconfig)? Jag tror att Prettier också använder den om man har det installerat.

**Comment by WoIfey** [comment]
EditorConfig fungerar med prettier 👍

![image](https://github.com/user-attachments/assets/0ef86f76-5eb8-4e72-8179-f8c86bc3cbd0)

**Comment by WoIfey** [comment]
VSCode har inte .editorconfig inbyggd och behöver en plugin för att fungera som Prettier eller [EditorConfig Plugin](https://marketplace.visualstudio.com/items?itemName=EditorConfig.EditorConfig)

**Comment by WoIfey** [comment]
Om det har .editorconfig inbyggt så behövs det inte plugins, jag föreslog dessa plugins om ingen har de ännu och använder vscode för de behövs 1 av de plugins.
