### ISSUE TITLE
Wireframe: login

### ISSUE THREAD

**Issue by tlebeitsuk** [tlebeitsuk/hoster#5]
Wireframe design förslag för autentisering (login).

Inloggningsalternativ:
- GitHub
- Google
- E-post och lösenord

Exempel:
- https://supabase.com/dashboard/sign-in
- https://www.justinmind.com/wp-content/webp-express/webp-images/uploads/2020/01/login-page-example-bondroy.png.webp

**Comment by z3kkeen** [comment]
![image](https://github.com/user-attachments/assets/19bd70fa-d1da-4ee0-b5e1-b7a7c38e9294)

![image](https://github.com/user-attachments/assets/850f9402-a349-4f83-999f-8e5f7182e708)

**Comment by LunaBorea** [comment]
Jacob och Nathanael

**Comment by Alasadi963** [comment]
![image-asset](https://github.com/user-attachments/assets/66eec2ae-75f0-46cd-abc5-9871959534eb)
![thumbnail-web-login-and-signup-wireframe-1200x900](https://github.com/user-attachments/assets/95688895-1588-41c2-bb1d-15d3922f00fc)

**Comment by Lugnas** [comment]
![Skärmbild 2024-10-09 145749](https://github.com/user-attachments/assets/4fa0a32a-70f1-4056-8690-2bda16962127)

**Comment by s5msepi0l** [comment]
![design](https://github.com/user-attachments/assets/2454858a-a7ea-4a0e-acdd-4268e76d4583)

**Comment by z3kkeen** [comment]
min
