### ISSUE TITLE
Wireframe: dashboard

### ISSUE THREAD

**Issue by tlebeitsuk** [tlebeitsuk/hoster#6]
Wireframe design förslag för kontrollpanelen när man loggat in.

Exempel:
- https://ui.shadcn.com/examples/music
- https://ui.shadcn.com/examples/dashboard
- https://dribbble.com/shots/21590789-Logip-Admin-Dashboard-Analytics-UX
- https://dribbble.com/shots/24191273-Sales-Analytics-Dashboard
- https://dribbble.com/shots/24748298-BordUp-HR-Recruitment-Dashboard

**Comment by Her0x00** [comment]
Erik och hannes

**Comment by EmrickF** [comment]
https://www.figma.com/design/Ljesl3gLZIRyDbHQ9FpPMB/Untitled?node-id=0-1&node-type=canvas&t=CChHv9rB5RNhCalH-0

**Comment by EmrickF** [comment]
![image](https://github.com/user-attachments/assets/e42c1c19-708b-436c-8070-a96b7b322139)

**Comment by EmrickF** [comment]
![image](https://github.com/user-attachments/assets/bc2abce5-05ef-488c-b36e-a66e18eadfa5)

**Comment by WoIfey** [comment]
👋
