### ISSUE TITLE
Wireframe: nytt projekt

### ISSUE THREAD

**Issue by tlebeitsuk** [tlebeitsuk/hoster#7]
Wireframe design för ett nytt projekt.

Fält:
- Namn
- Beskrivning

Exempel:
- https://dribbble.com/shots/19634610-Create-new-project-admin-panel-ui-design
- https://dribbble.com/shots/17472097-Daily-UI-090-Create-New
- https://dribbble.com/shots/14968453-Daily-UI-090-Create-New

**Comment by moa-byggmastar** [comment]
Moa och Rei

**Comment by moa-byggmastar** [comment]
<img width="515" alt="wireframe" src="https://github.com/user-attachments/assets/5934f264-ebf8-488d-8ac7-583b00517d4b">

**Comment by Steekmen** [comment]
Jag tar den här

**Comment by tlebeitsuk** [comment]
#20
